// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIG0ArjuO74lvQwm0V_4fiveWHjg_PRqw',
    appId: '1:996015186986:web:964368dd736917345f0f53',
    messagingSenderId: '996015186986',
    projectId: 'fluttertestfirebase01',
    authDomain: 'fluttertestfirebase01.firebaseapp.com',
    storageBucket: 'fluttertestfirebase01.appspot.com',
    measurementId: 'G-83BST8LVFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3IaolmQwbKYaXXA1HgR5tNaQqBJ-ekcA',
    appId: '1:996015186986:android:a1ec46a431fe4bd95f0f53',
    messagingSenderId: '996015186986',
    projectId: 'fluttertestfirebase01',
    storageBucket: 'fluttertestfirebase01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvvAifQqnerwiGfoqph_bRRHt2vQKqDM',
    appId: '1:996015186986:ios:be072786e55a951f5f0f53',
    messagingSenderId: '996015186986',
    projectId: 'fluttertestfirebase01',
    storageBucket: 'fluttertestfirebase01.appspot.com',
    iosClientId: '996015186986-hlumnn4ir6vruk5nmtsccjkco1gln109.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseConfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvvAifQqnerwiGfoqph_bRRHt2vQKqDM',
    appId: '1:996015186986:ios:be072786e55a951f5f0f53',
    messagingSenderId: '996015186986',
    projectId: 'fluttertestfirebase01',
    storageBucket: 'fluttertestfirebase01.appspot.com',
    iosClientId: '996015186986-hlumnn4ir6vruk5nmtsccjkco1gln109.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseConfig',
  );
}
