# entero = 20
# def primo(numero):
#     if numero < 2:
#         return False
#     for i in range(2, int(numero ** 0.5) + 1):
#         if numero % i == 0:
#             return False
#     return True
# def sumatoria_primos(n):
#     suma = 0
#     for i in range(2, n + 1):
#         if primo(i):
#             suma += i
#     return suma
# resultado = sumatoria_primos(entero-1)
# print("La suma hasta el entero: ", entero, " es: ", resultado)










# import pandas

# x=[2,4,6,8,10]
# y=[1,3,5,7,9]
# z=5

# if(x.index):
#     (x.)


